<?php
$title = "Literature Review";
$description2 = "Literature Review About Ethics and the World Wide Web.";
include '../inc/header.php';
?>
				<div id="literature-review">
					<h3>Student: 733474</h3>
					<h3>Subject: Ethics and the World Wide Web</h3>

					<h5>Introduction</h5>
						<p>In this review is an examination of ethics within the whole of World Wide Web also known as WWW or just Web. It will include the topic of what’s ethically right and wrong with the Web at the moment. Ethics is something known as moral thinking which defines something as ethically right or wrong. It can also be known as something which is unmoral or moral. Everyone thinks different as to what’s ethically right and what’s wrong. And The World Wide Web is something where loads of pages are linked together for user to view. People mostly get mistaken and think World Wide Web is the internet. These pages can be view by a web browser, such as Google Chrome, Internet Explorer etc. Hyper-Text Transfer Protocol (HTTP) is what transfers these Web pages to your device.</p>
						<p>This review will include a big, major topic of web privacy and how open the web is. Web privacy is a big issue within the World Wide Web.</p>
						<h6>Information Privacy/Web Openness</h6>
						<p>There have been many studies made that have investigated how the World Wide Web has destroyed human lives which suggest that the web has ethical problems within it, it is destroying lives for many reasons. These studies blame these problems on different things and have different views on it but mostly agree on most things as well as different ways of overcoming this problems of web ethics and privacy.
						<p>The web has many privacy problems because of its openness.
						<p>Even though human themselves have built this themselves, the World Wide Web has been affecting humans in a downside as “we have built Web infrastructure without considering privacy, we are also endangering our basic freedoms” (Moglen, 2013, p1). So what Moglen is saying is that humans are the ones to blame as there were no privacy measures in place when web was first built, but even with the technology now nothing is being done or even trying to be done, when something could be done. Therefore humans themselves are their own downfall. Personal informing is been taking from peoples own devices because of this web infrastructure through the system called data miming, this is being taking for themselves to help them and their business and not for humans benefit. This system “is being used to spy on us” as Moglen has suggested. A comparison has been made between Mogel’s and Wel & Royakkers’s studies. Wel & Royakkers have said that “web mining... [poses] a threat to some important ethical values like privacy and individuality. Web mining makes it difficult for an individual to autonomously control the unveiling and dissemination of data about his/her life” (Wel & Royakkers, 2004). Both studies have similarities and both suggested that data mining is a case of terrorising individual privacy. So what this means is that an individual cannot protect themselves from others from getting their information as web mining will take information from the user without any notification. So if information is being taking from the users, does every single user know that this is happening? But that’s not the case, so if information is being taking from them surely the least ethically thing to do is let them know, isn’t it?</p>
						<p>However as there is no privacy available on the web now it can be a advantage as you can find any information such as information on a new employee which they might be trying to hide whereas with privacy installed this wouldn’t happen. This stops the most basic right to be alone in peoples own thoughts and life. However in comparison another study has blamed it on web browsers and its developers. This study is from Woodbury’s investigation she says “the design of web browsers has resulted in a transfer of power to web user and developers who often lack an ethical framework” (Woodbury, 1998, p1). Woodbury thinks that web browser developers have not put any privacy measures in place because these developers have no moral integrity.</p>
						<p>Talking about information Wyatt has investigated about web and its information and its impact on web.
						<p>The web is too open for normal average users to use as one study has agreed with “Although surfing the web provides an excellent method... unless we evaluate the quality... we risk drowning in a sea of poor quality information” (Wyatt, 1997, p1). However as Wyatt has said that we risk of drowning in poor quality information is not right as if user were searching in the correct places and correct way it will eliminate this. But there is too many average users are using web and providing false information for others to use. This is also a problem as anyone can make a website with any information they want to include. “Since internet philosophy declares that anyone can set up a web site there is a risk that, through ignorance or bias, the content of the site may not be correct even if the original information sources were reliable” (Wyatt, 1997, p1). Wyatt has said that the internet can’t really be trusted with all this information being put online without any verification.</p>
						<p>In contrast Moglen thinks it needs to be more open , he thinks “the net should now universalize that process throughout the human race, should make it possible every person on Earth to read, watch, listen and participate in every form of learning and culture, everywhere, without discrimination between rich and poor, old and young, male and female” (Moglen, 2013, p1). He wants everyone to be able to use the web with no kind of discrimination so everyone can benefit from this system. If It were to be more open it will cause more problems.</p>
						<p>As the web is so open it will help kids grow up in this lifetime backed up by Moglen’s studies, “the last generation is being born whose brains will develop independently of the net” (Moglen, 2013, p1).  The kids nowadays can literally find anything on the web and learn from it which both be a bad thing as well as a good thing as they might find and read/see something which they wasn’t supposed to see/read which might mentally scare them or “develop” their brain as Moglen has called it in his investigation.</p>
						<p>These kids could also suddenly come across some pornographic images which happens quite too often as Newman had found during his investigations, he was surfing the web like one does when he came across to a “web page that appeared on my monitor contained advertisements for fee-based pornographic web sites and a suggestive image of a nude woman” (Newman, 2002, p1). Not only is this morally not right it’s not even good for anyone who sees as they could be mentally scarred from this as they weren’t expecting to see this kind of images. Newman also said that he was “disturbed by the level of control that an unknown person had exerted over my computer” (Newman, 2002, p1). The web page creator has allowed everyone who views this page to be able to view these images he/she should have more ethics code for themselves as they are a controller of this page.</p>
						<p>In Moglen’s study he has stated that the only way the privacy problems can be solved is by rebuilding “responsible replacement software, providing existing functions in ways that respect users’ privacy, to replace systems that are hazardous to privacy” (Moglen, 2013, p2). But there are already systems in place so therefore all it needs is to be altered and fixed to solve this privacy problem, and not go to the great length and rebuild something which is already there. But maybe this is the only way as everything is so bad nothing is working as it should be.</p>

					<h5>Conclusion</h5>
						<p>In conclusion, there is so many problems within Web, there are many more problems than first anticipated. All these examples and investigations from other people’s studies shows that the World Wide Web has got ethical problems within it. Web is too open, it has no privacy it allows anyone to steal other people’s information without them knowing or asking. This is proved by the system of data mining as well as random uses stealing others work. .And as Newman has said it allows web site developers to have control over their page users and the user can’t do anything about it. All studies have all agreed on that there is privacy problems that need to be corrected.</p>
						<p>If there is already investigations that have stated that there are these problems why isn’t no one doing anything to help it. All these are not morally correct and everyone knows it. There is no moral integrity built in within web. So does this mean that web is not ethical at all? As Moglen established that there’s only one way of fixing this problem by starting again because everything is so bad at the moment.
						<p>Not one study investigated talked or even mentioned about why these ethics were not put in place in the first place to stop this all happening. And why no one is doing anything to sort it. Everyone just investigated about what problems there are.</p>

					<h5>Bibliography</h5>
						<p>Moglen, E. (2013). The Tangled Web We Have Woven. Communications of the ACM, 56(2), 20-22. doi:10.1145/2408776.2408784</p>
						<p>Newman D. V. (2002). Impersonal interaction and ethics on the World-Wide-Web. Ethics and Inf. Technol. 3, 4 (January 2002), 239-246. DOI=10.1023/A:1013880620609 </p>
						<p>Wel, L. V., & Royakkers, L. (2004). Ethical issues in web data mining. Ethics and Inf. Technol., 6. </p>
						<p>Woodbury, M. (1998). Defining web ethics. Science and Engineering Ethics, 4(2), 203-212. doi:10.1007/s11948-998-0050-x</p>
						<p>Wyatt, J. C. (1997). Commentary: Measuring Quality and Impact of the World Wide Web. British Medical Journal. </p>
				</div>
<?php
include '../inc/footer.html';
?>